### ISSUE TITLE
Write BC

### ISSUE THREAD

**Issue by fl012** [TTRSF/TINF22F-Nameplate-Generator#4]
It describes the economic background of the project.

Requirements:

- 2-3 pages
- templates: look up repositories of previous classes
- methods: full cost accounting, partial cost accounting, risk analysis
- cost accounting: fix costs and costs for different work packages/ stages
- profitability calculation: how to scale money
- first general overview of project via GANTT-chart

**Comment by Quax2013** [comment]
- Cost accounting done
- Risk overview done
- Profitability partially done
- Missing GANTT-chart from time calculations
